Modules/Fotradis/Http/routes.php
  Route::get('/registrobenef/geteditpasajero/{id}', 'RegistroBenefController@showMdl_editPasajero')->name('registrobenef.geteditpasajero');      //Obtiene los datos para el formulario Editar pasajero.    Para mandar a llamar por nombre se hace: 'registrobenef.geteditpasajero[id]'
  Route::get('/registrobenef/getwatchpasajero/{id}', 'RegistroBenefController@showMdl_watchPasajero')->name('registrobenef.getwatchpasajero');   //Obtiene los datos del pasajero para el formulario en modo lectura.
  Route::post('/registrobenef/setstorepasajero', 'RegistroBenefController@storePasajero')->name('registrobenef.setstorepasajero');               //Guarda los datos del formulario Agregar pasajero.
  Route::post('/registrobenef/setupdatepasajero/{id}', 'RegistroBenefController@updatePasajero')->name('registrobenef.setupdatepasajero');        //Actualiza los datos del formulario Editar pasajero.
  Route::get('/registrobenef/getdeleteservicio/{id}', 'RegistroBenefController@showMdl_deleteServicio')->name('registrobenef.getdeleteservicio'); //Obtiene los datos para borrar un servicio de pasajero.
  Route::post('/registrobenef/setdeleteservicio', 'RegistroBenefController@deleteServicio')->name('registrobenef.setdeleteservicio');            //Obtiene los datos para borrar un servicio de pasajero.

  Route::get('/registrobenef/getpagarservicio/{id}', 'RegistroBenefController@showMdl_pagarServicio')->name('registrobenef.getpagarservicio');   //Obtiene los datos para el formulario Pagar servicio.
  Route::post('/registrobenef/setstorepagoserv', 'RegistroBenefController@storePagoServicio')->name('registrobenef.setstorepagoserv');           //Guarda los datos del formulario Pagar servicio.

  Route::get('/registrobenef/tiposservicio', 'RegistroBenefController@getTiposServicio')->name('registrobenef.getTiposServicio');                //Obtiene datos para el select Tipos de servicio
  Route::get('/registrobenef/tipospasajero', 'RegistroBenefController@getTiposPasajero')->name('registrobenef.getTiposPasajero');                //Obtiene datos para el select Tipos de pasajero
  Route::get('/registrobenef/paises', 'RegistroBenefController@getPaises')->name('registrobenef.getPaises');                                     //Obtiene datos para el select Países
  Route::get('/registrobenef/entidades', 'RegistroBenefController@getEntidades')->name('registrobenef.getEntidades');                            //Obtiene datos para el select entidades
  Route::get('/registrobenef/municipios', 'RegistroBenefController@getMunicipios')->name('registrobenef.getMunicipios');                         //Obtiene datos para el select Municipios
  Route::get('/registrobenef/lugarpago', 'RegistroBenefController@getLugaresDePago')->name('registrobenef.getLugaresPago');                      //Obtiene datos para el select Lugares de pago
  Route::get('/registrobenef/etnias', 'RegistroBenefController@getEtnias')->name('registrobenef.getEtnias');                      //Obtiene datos para el select Lugares de pago

  Route::put('/registrobenef/updatefoto/{persona_id}', 'RegistroBenefController@updateFoto')->name('registrobenef.updateFoto');

  Route::get('/registrobenef/draftrepinscritos', 'RegistroBenefController@showMdl_ReporteInscritos')->name('registrobenef.draftrepinscritos');
  Route::get('/registrobenef/repinscritos', 'RegistroBenefController@ReporteInscritos')->name('registrobenef.repinscritos');
  // -------------------------------------------------------------------------------------------------------------------------
  Route::resource('peticiones', 'PeticionController', ['as' => 'fotradis', 'only' => ['index', 'show', 'update', 'destroy']]);                            //Peticiones
  Route::resource('programas', 'ProgramaController', ['as' => 'fotradis']);                                                                         //Programas
  Route::resource('peticiones.beneficiarios', 'PeticionBeneficiarioController', ['except' => ['index'], 'as' => 'fotradis']);                   //Beneficiarios
  // *************************************************************************************************************************
  // -------------------------------------------------------------------------------------------------------------------------
  // *************************************************************************************************************************

  Route::get('/', 'FotradisController@index')->name('fotradis.index');
  Route::get('select/controlrutas', 'FotradisController@select_rutas')->name('controlrutas.select');
  Route::get('select/controlunidades', 'FotradisController@select_unidades')->name('controlunidades.select');
  Route::get('select/controlconductores', 'FotradisController@select_conductores')->name('controlconductores.select');
  Route::get('/historial', 'FotradisController@historial')->name('fotradis.historial');
  Route::get('/pasajeros/{unidad}', 'FotradisController@pasajerosABordo')->name('fotradis.abordo');
  Route::resource('controlrutas', 'FotradisController', ['except' => ['index', 'historial']]);
  Route::resource('fotradis', 'FotradisController', ['except' => ['index', 'historial']]);
  //Conductor
  Route::resource('conductor', 'DriverController', ['except' => ['update']]);
  Route::post('conductor/{conductor}', 'DriverController@update')->name('conductor.update');
  Route::delete('licencia/{licencia}', 'DriverController@destroyLicencia');
  Route::get('licencia/search/{licencia}', 'DriverController@searchLicencia');
  Route::get('conductor/search/{persona_id}/{conductor_id}', 'DriverController@search');
  Route::get('/licencias', 'DriverController@licenciaSelect')->name('licencias.fotradis.select');
  Route::get('/empleados/conductores', 'DriverController@empleadoSelect')->name('empleados.fotradis.select');
  Route::get('entidades', 'DriverController@entidadSelect')->name('entidades.select');
  Route::post('/crear/licencia', 'DriverController@crearLicencia')->name('fotradis.crear.licencia');
  //Unidad
  Route::resource('unidad', 'UnityController', ['except' => ['update']]);
  Route::post('unidad/{unidad}', 'UnityController@update')->name('unidad.update');
  //Tarjeta circulación
  Route::resource('tarjetacirculacion', 'TarjetaCirculacionController');
  //Rutas
  Route::resource('rutas', 'RoutesController', ['except' => ['edit', 'update']]);
  Route::post('parada/store', 'RoutesController@edit')->name('parada.store');
  Route::post('save/polyline', 'RoutesController@savePolyline')->name('parada.updatePolyline');
  Route::get('show/parada/{parada_id}/{ruta_id}', 'RoutesController@show_parada');
  Route::delete('ruta/parada/{ruta_id}/{parada_id}', 'RoutesController@update');
  Route::resource('bitacora', 'BitacoraController');
  Route::get('/conductor/ruta/asignacion', 'FotradisController@getConductorRuta')->name('conductor.ruta.asignacion');
  //Registro Pasajeros
  Route::post('pasajeros', 'FotradisController@saveRegistroPasajero')->name('pasajero.save');
  //Obtener asignación con número de unidad
  Route::get('asignacion/{numero_unidad}', 'FotradisController@getAsignacion')->name('asignacion.get');
  Route::get('mantenimiento/{unidad_id}', 'UnityController@listaMantenimiento');
  Route::post('mantenimiento', 'UnityController@agregarMantenimiento');
  //Estadisticas del home
  Route::get('/estadisticas', 'FotradisController@stats')->name('fotradis.stats');
  //Detalles de sesion
  Route::get('/sesion/{id}', 'FotradisController@Details');

  Route::resource('periodorecorridos', 'PeriodoRecorridoController');

  Route::post('/info', 'InfoAppController@servicios');
  Route::post('/bitacora', 'InfoAppController@bitacora');
  Route::post('/mantenimiento', 'InfoAppController@mantenimiento');
  Route::post('/heatmapdata', 'InfoAppController@coordenadas');



  //DTLL index de peticiones incompletas
  Route::get('/routes/incompletes', 'RoutesController@IncompleteRoutes')->name('rutas.incompletas');
});

Route::post('/dtll/api/takeAccess', 'Modules\Fotradis\Http\Controllers\API\ApiController@login'); //valida clave de conductor, da acceso al api | test = ok

Route::group(['middleware' => 'api', 'prefix' => 'dtll/api', 'namespace' => 'Modules\Fotradis\Http\Controllers\API'], function () {
  Route::get('/routes', 'RouteController@index');            //Regresa los recorridos disponibles                                      | test = ok
  Route::get('/route/{id}', 'RouteController@show');         //Regresa los datalles de un unico recorrido                              | test = ok
  Route::get('/traveler/{id}', 'TravelerController@show');   //valida clave de pasajero, regresa los datos o null                      | test = ok
  Route::get('/vans', 'VehicleController@list');             //obtener unidades que no se encuentren asignadas en el dia(filtrando)    | test = ok
  Route::get('/van/{id}', 'VehicleController@status');       //saber si se ha registrado km inicial, final o carga de gasolina         | test = ok
  Route::get('/drivers', 'DriverController@list');           //obtener conductores que no se encuentren asignados en el dia(filtrando) | test = ok
  Route::get('/driver/{id}', 'DriverController@show');
  Route::post('/recorder/km', 'VehicleController@addKm');    //registrar km inicial o final                                            | test = ok
  Route::post('/recorder/gas', 'VehicleController@addGas');  //registrar cargas de gasolina                                            | test = ok
  Route::post('/session', 'ApiController@appLogIn');         //regitstrar asignaciones                                                 | test = ok
  Route::delete('/session/{id}', 'ApiController@appLogOut'); //removerasignaciones                                                     | test = ok
  Route::post('/traveler/add', 'TravelerController@add');    //registrar el abordaje de un beneficiario                                | test = ok

Modules/Fotradis/Http/Controllers/API/DriverController.php
<?php

namespace Modules\Fotradis\Http\Controllers\API;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Routing\Controller;

use App\Models\Conductor;

class DriverController extends Controller{
    /**
     * Display a listing of the resource.
     * @return Response
     */
    public function list(Request $request){
      $conductores = Conductor::leftjoin('empleados','empleados.id','conductores.empleado_id')
      ->leftjoin('personas','personas.id','empleados.persona_id')
      ->leftjoin('controlrutas',function($query){
        $query->on('controlrutas.conductor_id','conductores.id')
        ->whereNull('controlrutas.deleted_at');
      })
      ->leftjoin('recorridos','recorridos.id','controlrutas.recorrido_id');
      if($request->filled('libre'))
        if($request->libre=='true')
          $conductores->whereNull('controlrutas.id');
        else if($request->libre=='false')
          $conductores->whereNotNull('controlrutas.id');
      return response()->json($conductores->get(['personas.nombre','primer_apellido','segundo_apellido','numero_celular','numero_local','persona_emergencia','telefono_emergencia','recorridos.nombre as ruta_actual','unidad_id as unidad_actual']));
    }

    /**
     * Show the specified resource.
     * @return Response
     */
    public function show($id){
      $driver = Conductor::leftjoin('empleados','empleados.id','conductores.empleado_id')
      ->leftjoin('personas','personas.id','empleados.persona_id')
      ->where('clave_conductor',$id)->firstOrFail(['personas.nombre','personas.primer_apellido','personas.segundo_apellido']);
      return $driver? response()->json($driver) : null;
    }

}

Modules/Fotradis/Resources/views/driver/js/conductor.blade.php
<script type="text/javascript">
	var app = (function() {

		var bloqueo = false;

		function to_upper_case() {
			$(':input').on('propertychange input', function(e) {
				var ss = e.target.selectionStart;
				var se = e.target.selectionEnd;
				e.target.value = e.target.value.toUpperCase();
				e.target.selectionStart = ss;
				e.target.selectionEnd = se;
			});
		};

		function set_bloqueo(valor) {
			bloqueo = valor;
		};

		function get_bloqueo() {
			return bloqueo;
		};

		function agregar_bloqueo_pagina() {
			$('form :input').change(function() {
				bloqueo = true;
			});

			window.onbeforeunload = function(e) {
				if(bloqueo)
				{
					return '¿Estás seguro de salir?';
				}
			};
		};

		return {
			to_upper_case: to_upper_case,
			set_bloqueo: set_bloqueo,
			agregar_bloqueo_pagina: agregar_bloqueo_pagina
		};
	})();

	var licencias = (function() {

		function select2_licencias() {
			$('#clave_licencia').select2({
		      language: 'es',
		      ajax: {
		        url: '{{ route('licencias.fotradis.select') }}',
		        dataType: 'JSON',
		        type: 'GET',
		        data: function(params) {
		          return {
		            search: params.term
		          };
		        },
		        processResults: function(data, params) {
		          params.page = params.page || 1;
		          return {
		            results: $.map(data, function(item) {
		              return {
		                id: item.numero_licencia,
		                text: item.numero_licencia,
		                slug: item.numero_licencia,
		                value: item.id,
		                results: item
		              }
		            })
		          };
		        },
		        cache: true
		      }
	  		});
		};

		function crear_licencia() {
			var form_modal_licencia = $("#form_modal_licencia");
			if(form_modal_licencia.valid()) {
				swal({
				title: '¿Estas seguro?',
				text: '¡Nueva licencia!',
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#28a745',
				cancelButtonColor: '#dc3545',
				confirmButtonText: 'SI',
				cancelButtonText: 'NO'
				}).then((result) => {
					if(result.value) {
						console.log("true");
						$.ajaxSetup({
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							}
						});

						var formData = new FormData(form_modal_licencia[0]);
						
 						$.ajax({
							url:  "{{ route('fotradis.crear.licencia') }}",
							type: 'POST',
							data: formData,
							dataType: 'JSON',
							processData: false, 
							contentType: false,
							success: function(response) {
								if(response.estatus == 'existente') {
									swal({
										title: '¡No se almaceno licencia!',
										text: 'Esta repetida...',
										type: 'error'
									});
								} else if(response.estatus == 'nuevo') {
									swal({
										title: '¡Transacción exitosa!',
										text: 'Se ha almacenado...',
										type: 'success'
									});
									$("#licencia_id").val($("#numero_licencia").val());
									$("#modal_elegir_licencia").modal("hide");
								}
							},
							error: function(response) {
								swal({
									title: '¡Registro rechazado!',
									text: 'No almacenado...',
									type: 'error'
								});
							}
						});
					} else {
						console.log("false");
					}
				});
			}
		};

		function ver_licencia(licencia_id) {
			$.ajaxSetup({
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				}
			});
				$.ajax({
				url:  "{{ URL::to('fotradis/licencia/search') }}" + "/" + licencia_id,
				type: 'GET',
				success: function(response) {
					$("#ver_licencia").html(response.html);
					$(".input_licencia").prop( "disabled", true );
					$("#modal_ver_conductor").modal("hide");
					$("#modal_ver_licencia").modal("show");
				},
				error: function(response) {
					$("#ver_licencia").html(response.html);	
					$("#modal_ver_licencia").modal("show");
				}
			});
		};

		function eliminar_licencia(licencia_id) {
			swal({
				title: '¿Estas seguro?',
				text:  '¡Se eliminara el registro!',
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#28a745',
				cancelButtonColor: '#dc3545',
				confirmButtonText: 'SI',
				cancelButtonText: 'NO'
				}).then((result) => {
					if(result.value) {
						console.log("true");
						$.ajaxSetup({
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							}
						});
							$.ajax({
							url:  "{{ URL::to('fotradis/licencia') }}" + "/" + licencia_id,
							type: 'DELETE',
							success: function(response) {
								swal({
									title: '¡Transacción exitosa!',
									text: 'Registro almacenado...',
									type: 'success'
								});
							},
							error: function(response) {
								swal({
									title: '¡Transacción rechazada!',
									text: 'Registro no almacenado...',
									type: 'error'
								});
							}
						});
					} else {
						console.log("false");
					}
				});
		};

		return {
			select2_licencias: select2_licencias,
			crear_licencia: crear_licencia,
			ver_licencia: ver_licencia,
			eliminar_licencia: eliminar_licencia
		};

	})();

	var empleados = (function() {
		var form = $("#form_modal_agregar_conductor");
		function select2_empleados() {
			$('#conductor').select2({
		      language: 'es',
		      ajax: {
		        url: '{{ route('empleados.fotradis.select') }}',
		        dataType: 'JSON',
		        type: 'GET',
		        data: function(params) {
		          return {
		            search: params.term
		          };
		        },
		        processResults: function(data, params) {
		          params.page = params.page || 1;
		          return {
		            results: $.map(data, function(item) {
		              return {
		                id: item.rfc,
		                text: item.nombre,
		                slug: item.rfc,
		                results: item
		              }
		            })
		          };
		        },
		        cache: true
		      }
	  		});
		};

		function agregar_validacion() {
			form.validate({
				rules: {
					conductor: {
						required: true
					}
				}
			});
		};

		function seleccionar_empleado(empleado) {
			if(form.valid()) {
				swal({
				title: '¿Estas seguro?',
				text: '¡Empleado seleccionado!',
				type: 'warning',
				showCancelButton: true,
				confirmButtonColor: '#28a745',
				cancelButtonColor: '#dc3545',
				confirmButtonText: 'SI',
				cancelButtonText: 'NO'
				}).then((result) => {
					if(result.value) {
						$.ajaxSetup({
							headers: {
								'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
							}
						});

						var rfc;
						if(empleado == '')
							rfc = $("#conductor").select2('data')[0].results.rfc;
						else
							rfc = empleado;

 						$.ajax({
							url:  "{{ URL::to('fotradis/conductor/create') }}" + "?rfc=" + rfc,
							type: 'GET',
							success: function(response) {
								swal({
									title: '¡Selección exitosa!',
									text: 'Registro encontrado...',
									type: 'success'
								});

								window.location.href = "{{ URL::to('fotradis/conductor/show') }}" + "?empleado=" + response.id;
							},
							error: function(response) {
								swal({
									title: '¡Selección cancelada!',
									text: 'Registro no encontrado...',
									type: 'error'
								});
							}
						});

					}
				});
			}
		};

		return {
			select2_empleados: select2_empleados,
			agregar_validacion: agregar_validacion,
			seleccionar_empleado: seleccionar_empleado
		};
	})();

	function elegir_licencia() {
		//$("#licencia_id").val($("#clave_licencia").select2('data')[0].results.numero_licencia);
		$("#licencia_id").val($("#numero_licencia").val());
	}

	function mostrar_modal_nueva_licencia() {
		$("#modal_nueva_licencia").modal("show");
	}

	function validar_modal_nueva_licencia() {
	    $('.datepicker').datepicker({
	        autoclose: true,
	        language: 'es',
	        format: 'yyyy-mm-dd'
	    }).change(function(event) {
	      //$(".datepicker").valid();  
	    });

	    select2_entidades();

	    $("#form_modal_licencia").validate({
			rules: {
				tipo: {
					required:true
				},
				numero_licencia: {
					required:true,
					pattern_numeros: true
				},
				fecha_expedicion: {
					required:true
				},
				vigencia: {
					required:true
				},
				oficina_expedidora: {
					required:true
				},
				entidad_id: {
					required:true
				}
			}
		});

	    $.validator.addMethod('pattern_numeros', function (value, element) {
	        return this.optional(element) || /\d+|(?:S\/N)|(?:s\/n)/.test(value);
	    }, 'Solo números');
	    
	    $("#modal_elegir_licencia").modal("show");
  }

function select2_entidades() {
	$('#entidad_id').select2({
	  language: 'es',
	  ajax: {
	    url: '{{ route('entidades.select') }}',
	    dataType: 'JSON',
	    type: 'GET',
	    data: function(params) {
	      return {
	        search: params.term
	      };
	    },
	    processResults: function(data, params) {
	      params.page = params.page || 1;
	      return {
	        results: $.map(data, function(item) {
	          return {
	            id: item.id,
	            text: item.entidad,
	            slug: item.entidad,
	            results: item
	          }
	        })
	      };
	    },
	    cache: true
	  }
	});
};

function crear_editar_conductor(empleado_id, conductor) {
	var form_conductor = $("#form_conductor");
	$.validator.addMethod('pattern_numeros', function (value, element) {
		        return this.optional(element) || /\d+|(?:S\/N)|(?:s\/n)/.test(value);
		    }, 'Ingresar 10 dígitos');

	form_conductor.validate({
			rules: {
				licencia_id: {
					required:true
				},
				donador_organos: {
					required:true,
				},
				restricciones: {
					required:true
				},
				padecimientos_medicos: {
					required:true
				},
				telefono_emergencia: {
					required:true,					
				},
				persona_emergencia: {
					required:true,
				}
			}
		});

		if(form_conductor.valid()) {
			swal({
			title: '¿Estas seguro?',
			text:  '¡Actualizando conductores!',
			type: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#28a745',
			cancelButtonColor: '#dc3545',
			confirmButtonText: 'SI',
			cancelButtonText: 'NO'
			}).then((result) => {
				if(result.value) {
					console.log("true");
					$.ajaxSetup({
						headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						}
					});

					var formData = new FormData(form_conductor[0]);
					formData.append('empleado_id', empleado_id);
					formData.append('clave_conductor', 'n/e');

						$.ajax({
						url:  form_conductor.attr('action'),
						type: form_conductor.attr('method'),
						data: formData,
						dataType: 'JSON',
						processData: false, 
						contentType: false,
						success: function(response) {
							swal({
									title: '¡Transacción exitosa!',
									text: 'Se ha modificado los conductores...',
									type: 'success'
								});
							//reiniciar_modal_nueva_licencia();
							window.location.href = "{{ route("conductor.index") }}";
						},
						error: function(response) {
							swal({
								title: '¡Transacción rechazada!',
								text: 'Registro no almacenado...',
								type: 'error'
							});
						}
					});
				} else {
					console.log("false");
				}
			});
		}
	}

	function eliminar_conductor(conductor) {
		swal({
			title: '¿Estas seguro?',
			text:  '¡Se eliminara el registro!',
			type: 'warning',
			showCancelButton: true,
			confirmButtonColor: '#28a745',
			cancelButtonColor: '#dc3545',
			confirmButtonText: 'SI',
			cancelButtonText: 'NO'
			}).then((result) => {
				if(result.value) {
					console.log("true");
					$.ajaxSetup({
						headers: {
							'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
						}
					});
						$.ajax({
						url:  "{{ URL::to('fotradis/conductor') }}" + "/" + conductor,
						type: 'DELETE',
						success: function(response) {
							swal({
								title: '¡Transacción exitosa!',
								text: 'Conductor eliminado...',
								type: 'success'
							});
              window.LaravelDataTables['conductores_actuales'].ajax.reload(null, false);
						},
						error: function(response) {
							swal({
								title: '¡Transacción rechazada!',
								text: 'Registro no almacenado...',
								type: 'error'
							});
						}
					});
				} else {
					console.log("false");
				}
			});
	}

	function ver_conductor(persona, conductor) {
		$.ajaxSetup({
			headers: {
				'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
			}
		});
			$.ajax({
			url:  "{{ URL::to('fotradis/conductor/search') }}" + "/" + persona + "/" + conductor,
			type: 'GET',
			success: function(response) {
				$("#body_modal_ver_conductor").html(response.html);
				$("#modal_ver_conductor").modal("show");
				$("#licencia_id").prop( "disabled", true );
				$("#donador_organos").prop( "disabled", true );
				$("#restricciones").prop( "disabled", true );
				$("#padecimientos_medicos").prop( "disabled", true );
				$("#persona_emergencia").prop( "disabled", true );
				$("#telefono_emergencia").prop( "disabled", true );
				$("#clave_conductor").prop( "disabled", true );

				$("#asignar_licencia").html(
					response.html2
                );
			},
			error: function(response) {
				$("#body_modal_ver_conductor").html(response.html);	
				$("#modal_ver_conductor").modal("show");
			}
		});
	}
</script>